services:
  # Backend
  thebrains:
    build: ./thebrains
    environment:
      - PYTHON_PATH=./thebrains
    volumes:
      - datastore:/app/data  # Using a named volume

  # Frontend
  salaryleague:
    build: ./salaryleague
    ports:
      - "4200:4200"
    depends_on:
      - thebrains

# You must define the volume name at the bottom of the file
volumes:
  datastore: